import os
import subprocess

class ResumeGenerator:
    def __init__(self):
        self.personal_info = {}
        self.skills = []
        self.work_experience = []
        self.education = []
        self.certifications = []
        self.projects = []

    def set_personal_info(self, name, location, phone, email, linkedin, github):
        self.personal_info = {
            "name": name,
            "location": location,
            "phone": phone,
            "email": email,
            "linkedin": linkedin,
            "github": github
        }

    def add_skill(self, category, skills_list):
        self.skills.append((category, skills_list))

    def add_work_experience(self, company, location, position, date_range, responsibilities):
        self.work_experience.append({
            "company": company,
            "location": location,
            "position": position,
            "date_range": date_range,
            "responsibilities": responsibilities
        })

    def add_education(self, institution, location, degree, gpa, date_range):
        self.education.append({
            "institution": institution,
            "location": location,
            "degree": degree,
            "gpa": gpa,
            "date_range": date_range
        })

    def add_certification(self, certification_name, institution, date):
        self.certifications.append({
            "certification_name": certification_name,
            "institution": institution,
            "date": date
        })

    def add_project(self, project_name, technologies, description, date):
        self.projects.append({
            "project_name": project_name,
            "technologies": technologies,
            "description": description,
            "date": date
        })

    def generate_latex(self):
        latex_content = """
        \documentclass[letterpaper,8pt]{article}
        \usepackage{fancyhdr, titlesec, enumitem, hyperref, tabularx, ragged2e}
        \pagestyle{fancy}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \renewcommand{\footrulewidth}{0pt}

        \begin{document}
        \begin{center}
        {\huge \scshape %s} \\ 
        {\small %s | %s | \href{mailto:%s}{%s} | \href{%s}{LinkedIn} | \href{%s}{GitHub}}
        \end{center}

        \section*{Skills}
        \begin{itemize}
        """ % (self.personal_info.get("name", ""), self.personal_info.get("location", ""), 
               self.personal_info.get("phone", ""), self.personal_info.get("email", ""), 
               self.personal_info.get("email", ""), self.personal_info.get("linkedin", ""), 
               self.personal_info.get("github", ""))

        for category, skills_list in self.skills:
            latex_content += f"\\item \textbf{{{category}}}: {', '.join(skills_list)}\n"

        latex_content += "\end{itemize}\n"

        latex_content += "\section*{Work Experience}\n"
        for exp in self.work_experience:
            latex_content += f"\\textbf{{{exp['company']}}} ({exp['location']}) \\ \textit{{{exp['position']}}} ({exp['date_range']})\\n"
            latex_content += "\begin{itemize}"
            for res in exp['responsibilities']:
                latex_content += f"\\item {res}\n"
            latex_content += "\end{itemize}\n"

        latex_content += "\section*{Education}\n"
        for edu in self.education:
            latex_content += f"\\textbf{{{edu['institution']}}} ({edu['location']}) \\ \textit{{{edu['degree']}}}, GPA: {edu['gpa']} ({edu['date_range']})\\n"

        latex_content += "\section*{Certifications}\n"
        for cert in self.certifications:
            latex_content += f"\\item {cert['certification_name']} - {cert['institution']} ({cert['date']})\\n"

        latex_content += "\section*{Projects}\n"
        for proj in self.projects:
            latex_content += f"\\textbf{{{proj['project_name']}}} ({proj['date']}) \\ \textit{{{proj['technologies']}}}\\n"
            latex_content += "\begin{itemize}"
            latex_content += f"\\item {proj['description']}\n"
            latex_content += "\end{itemize}\n"

        latex_content += "\end{document}"

        return latex_content

    def save_as_pdf(self, output_filename="resume.pdf"):
        latex_code = self.generate_latex()
        tex_filename = "resume.tex"

        with open(tex_filename, "w") as f:
            f.write(latex_code)

        try:
            subprocess.run(["pdflatex", tex_filename], check=True)
            os.rename("resume.pdf", output_filename)
            print(f"PDF generated successfully: {output_filename}")
        except subprocess.CalledProcessError as e:
            print("Error occurred while generating PDF:", e)
        finally:
            # Clean up auxiliary files generated by pdflatex
            for ext in ["aux", "log", "out", "tex"]:
                if os.path.exists(f"resume.{ext}"):
                    os.remove(f"resume.{ext}")